# Generated by Django 3.1.7 on 2021-09-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='decription',
            new_name='description',
        ),
    ]
